easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Job
        - App\Entity\User
    design:
#        brand_color: '#1ABC9C'
        brand_color: 'rgba(26, 188, 156, 0.85)'
    user:
        display_name: true